/* ============================================================
   Atlas — Shared Road Data
   Loaded before map.js and stats.js so both can reference ROADS.
   ============================================================ */

const ROADS = [
  // ── West Coast ──────────────────────────────────────────────
  {
    name: 'Pacific Coast Highway',
    designation: 'Hwy 1',
    state: 'California',
    region: 'West Coast',
    type: 'Coastal',
    length: '656 mi',
    difficulty: 'Easy–Moderate',
    bestSeason: 'Year-round',
    highlight: 'Dramatic sea cliffs from Malibu to Mendocino',
    lat: 35.70, lng: -121.30,
  },
  {
    name: 'Angeles Crest Highway',
    designation: 'CA-2',
    state: 'California',
    region: 'West Coast',
    type: 'Mountain',
    length: '66 mi',
    difficulty: 'Moderate',
    bestSeason: 'May–Nov',
    highlight: 'Switchbacks above 7,000 ft over Los Angeles',
    lat: 34.25, lng: -117.90,
  },
  {
    name: 'North Cascades Highway',
    designation: 'WA-20',
    state: 'Washington',
    region: 'West Coast',
    type: 'Mountain',
    length: '140 mi',
    difficulty: 'Moderate',
    bestSeason: 'Jun–Oct',
    highlight: 'Volcanic peaks and glacial valleys',
    lat: 48.50, lng: -120.70,
  },
  {
    name: 'Cascade Lakes Scenic Byway',
    designation: 'OR-46',
    state: 'Oregon',
    region: 'West Coast',
    type: 'Scenic',
    length: '66 mi',
    difficulty: 'Easy',
    bestSeason: 'Jul–Oct',
    highlight: 'Alpine lakes flanking the Cascades',
    lat: 43.90, lng: -121.70,
  },
  {
    name: 'Rim of the World Drive',
    designation: 'CA-18',
    state: 'California',
    region: 'West Coast',
    type: 'Mountain',
    length: '40 mi',
    difficulty: 'Moderate',
    bestSeason: 'Apr–Nov',
    highlight: 'Ridge-top drive over the San Bernardino mountains',
    lat: 34.17, lng: -117.05,
  },
  {
    name: 'Rogue–Umpqua Scenic Byway',
    designation: 'OR-62 / OR-230',
    state: 'Oregon',
    region: 'West Coast',
    type: 'Scenic',
    length: '172 mi',
    difficulty: 'Easy',
    bestSeason: 'May–Oct',
    highlight: 'Waterfalls, canyons, and Crater Lake approaches',
    lat: 43.20, lng: -122.90,
  },
  {
    name: 'Hana Highway',
    designation: 'HI-360',
    state: 'Hawaii',
    region: 'West Coast',
    type: 'Coastal',
    length: '64 mi',
    difficulty: 'Moderate',
    bestSeason: 'Year-round',
    highlight: '617 curves, 59 bridges, and lush Maui jungle',
    lat: 20.80, lng: -156.20,
  },
  {
    name: 'Seward Highway',
    designation: 'AK-1',
    state: 'Alaska',
    region: 'West Coast',
    type: 'Scenic',
    length: '127 mi',
    difficulty: 'Easy–Moderate',
    bestSeason: 'Jun–Sep',
    highlight: 'Fjords, glaciers, and bald eagles from Anchorage',
    lat: 60.40, lng: -149.40,
  },
  // ── Mountain West ────────────────────────────────────────────
  {
    name: 'Beartooth Highway',
    designation: 'US-212',
    state: 'Montana / Wyoming',
    region: 'Mountain West',
    type: 'Mountain',
    length: '68 mi',
    difficulty: 'Challenging',
    bestSeason: 'Jun–Sep',
    highlight: "America's most beautiful road — 10,947 ft summit",
    lat: 45.03, lng: -109.54,
  },
  {
    name: 'Going-to-the-Sun Road',
    designation: 'GTSR',
    state: 'Montana',
    region: 'Mountain West',
    type: 'Mountain',
    length: '50 mi',
    difficulty: 'Moderate',
    bestSeason: 'Jul–Sep',
    highlight: 'Glacier NP — narrow ledge road at Logan Pass',
    lat: 48.70, lng: -113.73,
  },
  {
    name: 'Million Dollar Highway',
    designation: 'US-550',
    state: 'Colorado',
    region: 'Mountain West',
    type: 'Mountain',
    length: '25 mi',
    difficulty: 'Very Challenging',
    bestSeason: 'Jun–Oct',
    highlight: 'No guardrails, sheer drops, three 11,000 ft passes',
    lat: 37.90, lng: -107.73,
  },
  {
    name: 'Trail Ridge Road',
    designation: 'US-34',
    state: 'Colorado',
    region: 'Mountain West',
    type: 'Mountain',
    length: '48 mi',
    difficulty: 'Moderate',
    bestSeason: 'Jun–Oct',
    highlight: 'Highest continuous paved road in the US at 12,183 ft',
    lat: 40.43, lng: -105.75,
  },
  {
    name: 'Chief Joseph Scenic Byway',
    designation: 'WY-296',
    state: 'Wyoming',
    region: 'Mountain West',
    type: 'Scenic',
    length: '46 mi',
    difficulty: 'Easy–Moderate',
    bestSeason: 'Jun–Oct',
    highlight: 'Dead Indian Pass and sweeping Absaroka views',
    lat: 44.70, lng: -109.60,
  },
  {
    name: 'Needles Highway',
    designation: 'SD-87',
    state: 'South Dakota',
    region: 'Mountain West',
    type: 'Mountain',
    length: '14 mi',
    difficulty: 'Moderate',
    bestSeason: 'May–Oct',
    highlight: 'Tunnels chiselled through granite spires',
    lat: 43.68, lng: -103.54,
  },
  {
    name: 'Iron Mountain Road',
    designation: 'SD-16A',
    state: 'South Dakota',
    region: 'Mountain West',
    type: 'Mountain',
    length: '17 mi',
    difficulty: 'Moderate',
    bestSeason: 'May–Oct',
    highlight: 'Pigtail bridges framing views of Mount Rushmore',
    lat: 43.85, lng: -103.44,
  },
  {
    name: 'Hells Canyon Scenic Byway',
    designation: 'ID-71',
    state: 'Idaho',
    region: 'Mountain West',
    type: 'Canyon',
    length: '218 mi',
    difficulty: 'Moderate',
    bestSeason: 'May–Oct',
    highlight: "North America's deepest river gorge",
    lat: 45.50, lng: -116.70,
  },
  {
    name: 'Lolo Pass Road',
    designation: 'US-12',
    state: 'Idaho / Montana',
    region: 'Mountain West',
    type: 'Mountain',
    length: '170 mi',
    difficulty: 'Moderate',
    bestSeason: 'May–Nov',
    highlight: 'Lewis & Clark route through the Bitterroot Range',
    lat: 46.60, lng: -114.60,
  },
  // ── Southwest ────────────────────────────────────────────────
  {
    name: 'Highway 12',
    designation: 'UT-12',
    state: 'Utah',
    region: 'Southwest',
    type: 'Scenic',
    length: '124 mi',
    difficulty: 'Moderate',
    bestSeason: 'Apr–Jun, Sep–Nov',
    highlight: "Bryce to Capitol Reef — arguably America's most beautiful road",
    lat: 37.77, lng: -111.56,
  },
  {
    name: 'Extraterrestrial Highway',
    designation: 'NV-375',
    state: 'Nevada',
    region: 'Southwest',
    type: 'Desert',
    length: '98 mi',
    difficulty: 'Easy',
    bestSeason: 'Sep–May',
    highlight: 'Dead-straight desert corridor past Area 51',
    lat: 37.50, lng: -115.37,
  },
  {
    name: 'Oak Creek Canyon',
    designation: 'AZ-89A',
    state: 'Arizona',
    region: 'Southwest',
    type: 'Canyon',
    length: '14 mi',
    difficulty: 'Moderate',
    bestSeason: 'Mar–Jun, Sep–Nov',
    highlight: 'Tight switchbacks dropping into a red-rock canyon',
    lat: 34.84, lng: -111.76,
  },
  {
    name: 'White Rim Road',
    designation: 'BLM Road',
    state: 'Utah',
    region: 'Southwest',
    type: 'Off-road',
    length: '100 mi',
    difficulty: 'Very Challenging',
    bestSeason: 'Mar–May, Sep–Oct',
    highlight: 'Canyonlands rim loop — 4WD required',
    lat: 38.18, lng: -109.88,
  },
  {
    name: 'Loneliest Road in America',
    designation: 'US-50',
    state: 'Nevada',
    region: 'Southwest',
    type: 'Desert',
    length: '287 mi',
    difficulty: 'Easy',
    bestSeason: 'Sep–May',
    highlight: 'Vast empty Nevada desert crossing 7 mountain ranges',
    lat: 39.50, lng: -117.00,
  },
  {
    name: 'Historic Route 66',
    designation: 'US-66',
    state: 'Various',
    region: 'Southwest',
    type: 'Historic',
    length: '2,278 mi',
    difficulty: 'Easy',
    bestSeason: 'Year-round',
    highlight: "The Mother Road — America's most iconic drive",
    lat: 35.10, lng: -106.60,
  },
  {
    name: 'Big Bend Ranch Road',
    designation: 'FM-170',
    state: 'Texas',
    region: 'Southwest',
    type: 'Desert',
    length: '50 mi',
    difficulty: 'Easy–Moderate',
    bestSeason: 'Oct–Apr',
    highlight: 'Remote Trans-Pecos canyon scenery along the Rio Grande',
    lat: 29.25, lng: -103.25,
  },
  {
    name: 'River Road',
    designation: 'TX-170',
    state: 'Texas',
    region: 'Southwest',
    type: 'Scenic',
    length: '56 mi',
    difficulty: 'Easy',
    bestSeason: 'Oct–Apr',
    highlight: 'Winding desert bluffs above the Rio Grande',
    lat: 29.50, lng: -104.60,
  },
  {
    name: 'Death Valley Scenic Loop',
    designation: "CA-190 / Artist's Drive",
    state: 'California',
    region: 'Southwest',
    type: 'Desert',
    length: '25 mi',
    difficulty: 'Easy',
    bestSeason: 'Oct–Apr',
    highlight: 'Salt flats, sand dunes, and volcanic crater loop',
    lat: 36.50, lng: -117.13,
  },
  {
    name: 'Geronimo Trail',
    designation: 'NM-152',
    state: 'New Mexico',
    region: 'Southwest',
    type: 'Mountain',
    length: '52 mi',
    difficulty: 'Moderate',
    bestSeason: 'Apr–Nov',
    highlight: 'Emory Pass summit at 8,228 ft over the Black Range',
    lat: 32.90, lng: -107.60,
  },
  // ── Southeast ────────────────────────────────────────────────
  {
    name: 'Tail of the Dragon',
    designation: 'US-129',
    state: 'North Carolina / Tennessee',
    region: 'Southeast',
    type: 'Technical',
    length: '11 mi',
    difficulty: 'Very Challenging',
    bestSeason: 'Apr–Nov',
    highlight: '318 curves, zero intersections — the world-famous dragon',
    lat: 35.47, lng: -83.98,
  },
  {
    name: 'Blue Ridge Parkway',
    designation: 'BRP',
    state: 'Virginia / North Carolina',
    region: 'Southeast',
    type: 'Scenic',
    length: '469 mi',
    difficulty: 'Easy',
    bestSeason: 'Apr–Nov',
    highlight: "America's Favourite Drive — ridge-top beauty for 469 miles",
    lat: 36.08, lng: -79.50,
  },
  {
    name: 'Cherohala Skyway',
    designation: 'TN-165 / NC-143',
    state: 'Tennessee / North Carolina',
    region: 'Southeast',
    type: 'Scenic',
    length: '43 mi',
    difficulty: 'Moderate',
    bestSeason: 'Apr–Nov',
    highlight: 'High-altitude ridge cruising through Cherokee National Forest',
    lat: 35.38, lng: -84.20,
  },
  {
    name: 'Moonshiner 28',
    designation: 'NC-28',
    state: 'North Carolina',
    region: 'Southeast',
    type: 'Technical',
    length: '38 mi',
    difficulty: 'Challenging',
    bestSeason: 'Apr–Nov',
    highlight: "Fast sweepers and elevation changes — Tail's secret sibling",
    lat: 35.27, lng: -83.42,
  },
  {
    name: 'Overseas Highway',
    designation: 'US-1',
    state: 'Florida',
    region: 'Southeast',
    type: 'Coastal',
    length: '113 mi',
    difficulty: 'Easy',
    bestSeason: 'Nov–Apr',
    highlight: '42 bridges connecting the Florida Keys to Key West',
    lat: 24.70, lng: -80.90,
  },
  {
    name: 'Natchez Trace Parkway',
    designation: 'NTP',
    state: 'Mississippi / Tennessee',
    region: 'Southeast',
    type: 'Historic',
    length: '444 mi',
    difficulty: 'Easy',
    bestSeason: 'Mar–May, Oct–Nov',
    highlight: 'Zero traffic lights, zero trucks — ancient American highway',
    lat: 34.70, lng: -87.70,
  },
  {
    name: 'Foothills Parkway',
    designation: 'FP',
    state: 'Tennessee',
    region: 'Southeast',
    type: 'Scenic',
    length: '72 mi',
    difficulty: 'Easy',
    bestSeason: 'Apr–Nov',
    highlight: 'Undiscovered Great Smoky Mountains ridge drive',
    lat: 35.65, lng: -83.85,
  },
  {
    name: 'Talimena Scenic Drive',
    designation: 'OK-1 / AR-88',
    state: 'Oklahoma / Arkansas',
    region: 'Southeast',
    type: 'Scenic',
    length: '54 mi',
    difficulty: 'Easy',
    bestSeason: 'Oct–Nov',
    highlight: 'Ouachita Mountain ridge with sweeping valley vistas',
    lat: 34.63, lng: -94.85,
  },
  // ── Northeast ────────────────────────────────────────────────
  {
    name: 'Kancamagus Highway',
    designation: 'NH-112',
    state: 'New Hampshire',
    region: 'Northeast',
    type: 'Scenic',
    length: '35 mi',
    difficulty: 'Easy',
    bestSeason: 'Sep–Oct',
    highlight: 'World-class fall foliage through White Mountain National Forest',
    lat: 44.05, lng: -71.40,
  },
  {
    name: 'Skyline Drive',
    designation: 'Shenandoah NP',
    state: 'Virginia',
    region: 'Northeast',
    type: 'Scenic',
    length: '105 mi',
    difficulty: 'Easy',
    bestSeason: 'May–Jun, Oct',
    highlight: '105 miles of ridge-top driving through Shenandoah NP',
    lat: 38.50, lng: -78.50,
  },
  {
    name: 'Vermont Route 100',
    designation: 'VT-100',
    state: 'Vermont',
    region: 'Northeast',
    type: 'Scenic',
    length: '216 mi',
    difficulty: 'Easy',
    bestSeason: 'Sep–Oct',
    highlight: 'Vermont spine road — covered bridges and peak fall colour',
    lat: 43.90, lng: -72.90,
  },
  {
    name: 'Mohawk Trail',
    designation: 'MA-2',
    state: 'Massachusetts',
    region: 'Northeast',
    type: 'Historic',
    length: '63 mi',
    difficulty: 'Easy–Moderate',
    bestSeason: 'Sep–Oct',
    highlight: "America's first scenic byway through the Berkshire highlands",
    lat: 42.67, lng: -73.00,
  },
  {
    name: 'Acadia Loop Road',
    designation: 'Park Loop Rd',
    state: 'Maine',
    region: 'Northeast',
    type: 'Coastal',
    length: '27 mi',
    difficulty: 'Easy',
    bestSeason: 'May–Oct',
    highlight: 'Rocky Atlantic coastline through Acadia National Park',
    lat: 44.32, lng: -68.22,
  },
  {
    name: 'Mount Washington Auto Road',
    designation: 'MWAR',
    state: 'New Hampshire',
    region: 'Northeast',
    type: 'Mountain',
    length: '7.6 mi',
    difficulty: 'Challenging',
    bestSeason: 'May–Oct',
    highlight: 'Steepest average grade of any auto road in the east — 6,288 ft summit',
    lat: 44.27, lng: -71.30,
  },
  // ── Midwest ──────────────────────────────────────────────────
  {
    name: 'Ozark Highlands Scenic Byway',
    designation: 'AR-7 / AR-21',
    state: 'Arkansas',
    region: 'Midwest',
    type: 'Scenic',
    length: '165 mi',
    difficulty: 'Moderate',
    bestSeason: 'Apr–Nov',
    highlight: 'Genuine switchbacks and technical bends through the Ozarks',
    lat: 35.75, lng: -93.40,
  },
  {
    name: 'Great River Road',
    designation: 'WI / MN scenic',
    state: 'Wisconsin / Minnesota',
    region: 'Midwest',
    type: 'Scenic',
    length: '250 mi',
    difficulty: 'Easy',
    bestSeason: 'May–Oct',
    highlight: 'Mississippi River bluffs, river towns, and bald eagles',
    lat: 44.00, lng: -91.50,
  },
  {
    name: 'Loess Hills Parkway',
    designation: 'IA-183',
    state: 'Iowa',
    region: 'Midwest',
    type: 'Scenic',
    length: '220 mi',
    difficulty: 'Easy',
    bestSeason: 'Apr–Nov',
    highlight: 'Rolling loess bluffs found only here and in China',
    lat: 42.05, lng: -96.05,
  },
  {
    name: 'Tunnel of Trees',
    designation: 'M-119',
    state: 'Michigan',
    region: 'Midwest',
    type: 'Scenic',
    length: '20 mi',
    difficulty: 'Easy',
    bestSeason: 'Sep–Oct',
    highlight: 'Canopy of hardwoods tunnels over Lake Michigan shoreline',
    lat: 45.45, lng: -85.00,
  },
];
